# Exec with: docker-compose run ros-dev
# ROS_IP and ROS_MASTER_URI must be Raspberry IP
version: "3.9"
   
services:

  ros-dev:
    build:
      context: .
      dockerfile: ./services/Dockerfile.dev
    network_mode: host
    privileged: true
    volumes:
      - ./src:/ros/src
      - /dev/ttyACM0:/dev/rosSerialClient
      - /dev/ttyUSB0:/dev/rosLidar
    working_dir: /ros
    stdin_open: true
    tty: true
    command: /bin/bash

  ros-run:
    build:
      context: .
      dockerfile: ./services/Dockerfile.run
    network_mode: host
    privileged: true
    volumes:
      - /dev/ttyACM0:/dev/rosSerialClient
      - /dev/ttyUSB0:/dev/rosLidar
    environment:
      - ROS_IP=192.168.1.120
      - ROS_MASTER_URI=http://192.168.1.120:11311
