# Exec with: docker-compose run ros-dev
version: "3.9"
   
services:

  ros-dev:
    build:
      context: .
      dockerfile: ./services/Dockerfile.dev
    network_mode: host
    privileged: true
    volumes:
      - ./src:/ros/src
      - /dev/serial0:/dev/serialArduino
    working_dir: /ros
    stdin_open: true
    tty: true
    command: /bin/bash

  ros-run:
    build:
      context: .
      dockerfile: ./services/Dockerfile.run
    network_mode: host
    privileged: true
    volumes:
      - /dev/serial0:/dev/serialArduino
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
